"""Initial migrate

Revision ID: 830a81dea103
Revises: 
Create Date: 2022-07-06 14:52:57.292386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830a81dea103'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
